### ISSUE TITLE
Parse coverage information generated by the crawler while running using grcov

### ISSUE THREAD

**Issue by marco-c** [marco-c/coverage-crawler#2]
Using grcov, the gcda files generated by Firefox should be parsed and stored as a JSON file.

**Comment by DGRamya** [comment]
Hello Marco, I am interested to work on this issue. I have sent an email regarding queries, please respond to that.

**Comment by DGRamya** [comment]
Hello @marco-c, is there any project setup document that I can use? I tried to setup by following the Readme, but I ran into the error below after executing "./crawler.py"

`selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.`

Steps followed to resolve:
1. Downloaded geckodriver and updated the path in PATH 
2. Updated crawler.py with below lines
# Webdriver uses Firefox Binaries from downloaded cov build
#driver = webdriver.Firefox(firefox_binary='firefox/firefox-bin')
driver = webdriver.Firefox(executable_path=r'/home/ramya/geckodriver.exe')

**Comment by rhcu** [comment]
Hi @DGRamya! 
You don't need to update the line with `firefox_binary`. It should point not to the `geckodriver.exe` but to `firefox-bin` as it is done in the code. 
I can suggest trying steps that are described [here](https://stackoverflow.com/questions/40208051/selenium-using-python-geckodriver-executable-needs-to-be-in-path) as it helped me to solve this problem.  
Hope, this will help. :)

**Comment by marco-c** [comment]
Here's an example of what happens for Firefox tests: https://dxr.mozilla.org/mozilla-central/source/testing/mozharness/mozharness/mozilla/testing/codecoverage.py.

Before executing the crawler, we should set up the env variables like that script does (#1 and #19).

After the execution of the crawler, in order to parse the data, we will need some support files (#20).

So to summarize, this issue depends (at least) on #1, #19 and #20. I would start with one of them.

**Comment by DGRamya** [comment]
Hello @marco-c,

1. JS_CODE_COVERAGE_OUTPUT_DIR environment variable is set.
2. No geckodriver error.
3. When ./crawler.py is executed, I get the below error
`StaleElementReferenceException: Message: The element reference of <a href="/en-US/contribute/events/"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed`

**Comment by marco-c** [comment]
Do you always see that error when running the crawler?

**Comment by rhcu** [comment]
As I have understood,  we need to run `grcov` on `.gcda` files that were downloaded into `JS_CODE_COVERAGE_OUTPUT_DIR` and `GCOV_PREFIX` directories to get parsed result to be stored in `JSON` format, while they are in binary.

In order to do this, we can construct a shell command in Python according to the pattern described in README of grcov: `grcov DIRECTORY[...] [-t OUTPUT_TYPE] [-s SOURCE_ROOT] [--token COVERALLS_REPO_TOKEN]` and to get the output in Python script. 

To do this,
1. Firstly, we need to download `grcov` from [here](https://github.com/marco-c/grcov/releases) and to extract into some new directory. 
2. As `OUTPUT_TYPE` we can use `Coveralls specific formats`: I can get `json` output with `-t coveralls`, right?
3. For this format, `SOURCE_ROOT` and  `COVERALLS_REPO_TOKEN` are required. Can you suggest, how can we get these arguments?
4. Do we need to consider `.gcno` files that are stored in `target.code-coverage-gcno.zip`?

Can you correct me if I am misleading?
Thanks

**Comment by marco-c** [comment]
In the JS_CODE_COVERAGE_OUTPUT_DIR we have info files, which are in a textual format, but can still be parsed with grcov.
In the GCOV_PREFIX directory, we have gcda files, which contain the coverage counters (e.g. how many times was a line executed). In order to parse them, we also need the gcno files, as the gcno files contain the structure of the code.

1. Yes. Filed #35 for this.
2. Yes.
3. SOURCE_ROOT shouldn't be required. For COVERALLS_REPO_TOKEN, you can use a placeholder value, as we are not going to use it.
4. Yes, the gcno files are required to parse the gcda files. I suggest playing a bit with gcov in order to understand how all this works (https://en.wikipedia.org/wiki/Gcov, e.g. try removing the gcno file and see if gcov can still parse the result, and so on).

**Comment by marco-c** [comment]
Fixed by #39.
